name: OPFake
author: Martin77Epic
version: 1.0.0
main: OPFake\Main
api: [1.0.0, 2.0.0]
load: POSTWORLD
commands:
  opfake:
      description: OPFake commands
      usage: "/opfake <player>"
      permission: m77e.opfake
  deopfake:
      description: DEOPFake command
      usage: "/deopfake <player>"
      permission: m77e.deopfake
permissions:
  m77e.opfake:
    description: "Allows the user to run the opfake command"
    default: op
  m77e.deopfake:
    description: "Allows the user to run the deopfake command"
    default: op

