name: OPFake
version: b1
api: [1.0.0]
main: OPFake\Main
load: POSTWORLD
author: Martin77Epic
commands:
  fakeop:
    description: "Fake op any!"
    usage: "/fakeop <player>"
    permission: m77e.fakeop
permissions:
  m77e.opfake
    description: "Allows to run opfake!"
    default: op
